export const ADDED = "Todos/added"
export const DELETED = "Todos/deleted"
export const TOGGOLED = "Todos/toggoled"
export const SELECTCOLOR = "Todos/selectcolor"
export const ALCOMPLETE = "Todos/allcomplete"
export const CLEARCOMPLETE = "Todos/clearcomplete"